buildAndDeployApk:
  stage: buildAndDeployApk
  before_script:
    - cd receivers/android
  script:
    - if [ -z "$ANDROID_VERSION_NAME" ] || [ -z "$ANDROID_VERSION_CODE" ]; then echo "Version name or code not specified. Skipping build."; exit 0; fi
    - ./gradlew --stacktrace assembleRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE
    - cp ./app/build/outputs/apk/release/app-release.apk /var/www/html/fcast-release.apk
    - echo $ANDROID_VERSION_CODE > /var/www/html/fcast-version.txt
  when: manual

buildAndDeployPlayStoreAab:
  stage: buildAndDeployPlayStoreAab
  before_script:
    - cd receivers/android
  script:
    - if [ -z "$ANDROID_VERSION_NAME" ] || [ -z "$ANDROID_VERSION_CODE" ]; then echo "Version name or code not specified. Skipping build."; exit 0; fi
    - ./gradlew --stacktrace bundlePlaystoreRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE
    - cp ./app/build/outputs/bundle/playstoreRelease/app-playstore-release.aab /var/www/html/fcast-playstore-release.aab
  when: manual
