stages:
  - buildAndDeployApk

variables:
  ANDROID_VERSION_NAME: 
    value: ""
    description: "Enter the version name here (e.g. 1.0.1)."
  ANDROID_VERSION_CODE: 
    value: ""
    description: "Enter the version code here (e.g. 1)."

buildAndDeployApk:
  stage: buildAndDeployApk
  script:
    - if [ -z "$ANDROID_VERSION_NAME" ] || [ -z "$ANDROID_VERSION_CODE" ]; then echo "Version name or code not specified. Skipping build."; exit 0; fi
    - ./receivers/android/gradlew --stacktrace assembleRelease -PversionName=$ANDROID_VERSION_NAME -PversionCode=$ANDROID_VERSION_CODE
    - cp ./app/build/outputs/apk/release/app-release.apk /var/www/html/fcast-release.apk
    - cp ./app/build/outputs/apk/release/app-release.apk /var/www/html/fastcast-release.apk
  when: manual
