
buildWebOS:
  stage: buildWebOSReceiver
  image: node:current-bookworm
  tags:
    - fcast-instance-runner
  before_script:
    - cd receivers/webos
    - npm install -g @webos-tools/cli
  script:
    - cd fcast-receiver
    - npm run build
    - cd ../fcast-receiver-service
    - npm run build
    - cd ../
    - ares-package fcast-receiver/dist/ fcast-receiver-service/dist/ --no-minify
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - receivers/webos/com.futo.fcast.receiver_1.0.0_all.ipk
  when: manual
