
buildWebOS:
  stage: buildWebOSReceiver
  image: node:16.20.2-bullseye
  tags:
    - fcast-instance-runner
  before_script:
    - cd receivers/webos
    - npm install -g @webos-tools/cli
    - cd fcast-receiver
    - npm install
    - cd ../fcast-receiver-service
    - npm install
    - cd ..
  script:
    - scripts/build.sh
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: "30 days"
    paths:
      - receivers/webos/*.ipk
  when: manual
